#!/usr/bin/env bash

apache_exists() {
	test -x "$(WHICH apache2)"
}

apache_list() {
	apache_exists && echo "apache2"
}

apache_name() {
	echo "The Apache Web Server"
}


apache_status() {
	applications_vv "$1" &>/dev/null
}

apache_version() {
	echo "$(applications_vv "$1")" | grep "Server version" | cut -d: -f2 | xargs
}