#!/usr/bin/env bash

apache_exists() {
	test -x "$(WHICH apache2)"
}

apache_list() {
	echo "apache2"
}

apache_name() {
	test "$1" == "apache" || test "$1" == "apache2"
}

apache_desc() {
	echo "The Apache Web Server"
}

apache_version() {
	echo "$(applications_vv "$1")" |grep "Server version"|cut -d: -f2
}

apache_status() {
	applications_vv "$1" &>/dev/null
}
