#!/usr/bin/env bash
#
# Apache functions

#######################################
# Check if application exist in the system
# Arguments:
#   None
# Outputs:
#   Show the list the pythons versions to stdout
#######################################
apache_application_list() {
	entry_function ${FUNCNAME} ${FUNCNAME[1]} "$@"

	check_program "apache2"
}

#######################################
# Show the name of application
# Arguments:
#   None
# Outputs:
#   Show the name of application to stdout
#######################################
apache_application_name() {
	entry_function ${FUNCNAME} ${FUNCNAME[1]} "$@"

	echo "The Apache Web Server"
}

#######################################
# Show the name of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   0 if application in run fine, non-zero application have a problem
#######################################
apache_application_status() {
	entry_function ${FUNCNAME} ${FUNCNAME[1]} "$@"

	applications_vv "$1" &>/dev/null
}

#######################################
# Show the version of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   Show the version of application to stdout
#######################################
apache_application_version() {
	entry_function ${FUNCNAME} ${FUNCNAME[1]} "$@"

	applications_vv "$1" | grep "Server version" | cut -d: -f2 | xargs
}
