#!/usr/bin/env bash

dbus_exists() {
	test -x "$(WHICH dbus-daemon)"
}

dbus_list() {
	dbus_exists && echo "dbus-daemon"
}

dbus_name() {
	echo "DBUS daemon"
}


dbus_status() {
	applications_version "$1" &>/dev/null
}

dbus_version() {
	echo "$(applications_version "$1")"
}