#!/usr/bin/env bash
#
# Dhclient functions

#######################################
# Check if application exist in the system
# Arguments:
#   None
# Outputs:
#   Show the list the command line versions to stdout
#######################################
dhclient_application_list() {
	entry_function "$@"

	check_program "dhclient"
}

#######################################
# Show the name of application
# Arguments:
#   None
# Outputs:
#   Show the name of application to stdout
#######################################
dhclient_application_name() {
	entry_function "$@"

	echo "Client DHCP"
}

#######################################
# Show the name of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   0 if application in run fine, non-zero application have a problem
#######################################
dhclient_application_status() {
	entry_function "$@"

	applications_version "$1" &>/dev/null
}

#######################################
# Show the version of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   Show the version of application to stdout
#######################################
dhclient_application_version() {
	entry_function "$@"

	applications_version "$1" 2>&1
}

#######################################
# Generate the necessary code for the monit configuration
# Arguments:
#   one command returned from the list of the xxxx_list function
# Outputs:
#   Show monit code
#######################################
dhclient_application_monit() {
	entry_function "$@"

	applications_cmd_monit "$1" net
}
