#!/usr/bin/env bash
#
# Fcron functions


#######################################
# Check if application exist in the system
# Arguments:
#   None
# Outputs:
#   Show the list the pythons versions to stdout
#######################################
fcron_list() {
	check_program "fcron"
}

#######################################
# Show the name of application
# Arguments:
#   None
# Outputs:
#   Show the name of application to stdout
#######################################
fcron_name() {
	echo "Fcron"
}

#######################################
# Show the name of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   0 if application in run fine, non-zero application have a problem
#######################################
fcron_status() {
	applications_version "$1" &>/dev/null
}

#######################################
# Show the version of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   Show the version of application to stdout
#######################################
fcron_version() {
	applications_version "$1"
}
