#!/usr/bin/env bash
#
# Python php

#######################################
# Check if application exist in the system
# Arguments:
#   None
# Outputs:
#   Show the list the pythons versions to stdout
#######################################
php_list() {
	local PHP

	for PHP in php php5 php5.{0..6} php7 php7.{0..4} php8 php8.{0..4}; do
		check_program "$PHP"
	done
}

#######################################
# Show the name of application
# Arguments:
#   None
# Outputs:
#   Show the name of application to stdout
#######################################
php_name() {
	echo "PHP language"
}

#######################################
# Show the name of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   0 if application in run fine, non-zero application have a problem
#######################################
php_status() {
	applications_status "$1"
}

#######################################
# Show the version of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   Show the version of application to stdout
#######################################
php_version() {
	applications_version "$1" | head -1
}
