#!/usr/bin/env bash
#
# php-fpm

#######################################
# Check if application exist in the system
# Arguments:
#   None
# Outputs:
#   Show the list the command line versions to stdout
#######################################
phpfpm_application_list() {
	entry_function "$@"

	local PHP

	for PHP in php-fpm php-fpm5 php-fpm5.{0..6} php-fpm7 php-fpm7.{0..4} php-fpm8 php-fpm8.{0..4}; do
		check_program "$PHP"
	done
}

#######################################
# Show the name of application
# Arguments:
#   None
# Outputs:
#   Show the name of application to stdout
#######################################
phpfpm_application_name() {
	entry_function "$@"

	echo "PHP language"
}

#######################################
# Show the name of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   0 if application in run fine, non-zero application have a problem
#######################################
phpfpm_application_status() {
	entry_function "$@"

	applications_status "$1"
}

#######################################
# Show the version of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   Show the version of application to stdout
#######################################
phpfpm_application_version() {
	entry_function "$@"

	applications_version "$1" | head -1
}

#######################################
# Generate the necessary code for the monit configuration
# Arguments:
#   one command returned from the list of the xxxx_list function
# Outputs:
#   Show monit code
#######################################
phpfpm_application_monit() {
	entry_function "$@"

	applications_cmd_monit "$1" www "$(basename "$1")"
}
