#!/usr/bin/env bash
#
# Python functions

#######################################
# Check if application exist in the system
# Arguments:
#   None
# Outputs:
#   Show the list the pythons versions to stdout
#######################################
python_list() {
	entry_function ${FUNCNAME} "$@"

	local PYTHON

	for PYTHON in python2 python2.7 python3 python3.{4..13}; do
		check_program "$PYTHON"
	done
}

#######################################
# Show the name of application
# Arguments:
#   None
# Outputs:
#   Show the name of application to stdout
#######################################
python_name() {
	entry_function ${FUNCNAME} "$@"

	echo "Python language"
}

#######################################
# Show the name of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   0 if application in run fine, non-zero application have a problem
#######################################
python_status() {
	entry_function ${FUNCNAME} "$@"

	applications_status "$1"
}

#######################################
# Show the version of application
# Arguments:
#   command to check for one returned from the list of the xxxx_list function
# Outputs:
#   Show the version of application to stdout
#######################################
python_version() {
	entry_function ${FUNCNAME} "$@"

	applications_version "$1"
}
