#!/usr/bin/env bash

APACHE_SERVICE_LIST=(apache2 apache2.service)

apache_service_list() {
	apache_service_exists && echo "apache2"
}

apache_service_cmd() {
	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		echo "apache"
		;;
	"${SMMS_INIT_SYSTEMD}")
		echo "apache.service"
		;;
	esac
}

apache_service_name() {
	echo "The Apache Web Server"
}

apache_service_info() {
	echo "$(applications_vv "$1")"
}

apache_service_status() {
	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		/etc/init.d/apache2 configtest && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		apache2ctl configtest && return
		;;
	esac

	return 1
}
