#!/usr/bin/env bash

apache_service_list() {
	entry_function ${FUNCNAME} "$@"

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		test -x /etc/init.d/apache2 && (
			echo apache2
			[[ "$1" != "only" ]] && echo apache2.service
		)
		;;
	"${SMMS_INIT_SYSTEMD}")
		test -e /lib/systemd/system/apache2.service && (
			echo apache2.service
			[[ "$1" != "only" ]] && echo apache2
		)
		;;
	esac
}

apache_service_cmd() {
	entry_function ${FUNCNAME} "$@"

	WHICH apache2
}

apache_service_name() {
	entry_function ${FUNCNAME} "$@"

	echo "The Apache Web Server"
}

apache_service_info() {
	entry_function ${FUNCNAME} "$@"

	applications_vv "$(apache_list)"
}

apache_service_status() {
	entry_function ${FUNCNAME} "$@"

	local mods

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		/etc/init.d/apache2 configtest &>/dev/null && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		case "$(getDistro)" in
		"${SMMS_OS_GENTOO}")
			mods="$(grep ^APACHE2_OPTS= /etc/conf.d/apache2 | cut -d\" -f2)"
			;;
		esac

		apache_list "${mods}" -t &>/dev/null && return
		;;
	esac

	return 1
}
