#!/usr/bin/env bash

apache_service_list() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	SMMS_SERVICE_INIT apache2.service apache2
}

# shellcheck disable=SC2120
apache_service_cmd() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	apache_application_list
}

apache_service_name() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	echo "The Apache Web Server"
}

apache_service_info() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	applications_vv "$(apache_service_cmd)"
}

apache_service_process() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	pgrep "$1"
}

apache_service_status() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	local mods

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		${SMMS_OPENRC_PATH}/apache2 configtest &>/dev/null && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		case "$(getDistro)" in
		"${SMMS_OS_GENTOO}")
			mods="$(grep ^APACHE2_OPTS= /etc/conf.d/apache2 | cut -d\" -f2)"
			;;
		esac

		apache_application_list "${mods}" -t &>/dev/null && return
		;;
	esac

	return 1
}
