#!/usr/bin/env bash

dhcpd6_service_list() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	SMMS_SERVICE_INIT dhcpd6.service dhcpd
}

# shellcheck disable=SC2120
dhcpd6_service_cmd() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	dhcpd_application_list
}

dhcpd6_service_name() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	echo "DHCPv6 Server Daemon"
}

dhcpd6_service_info() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	applications_vv "$(dhcpd6_service_cmd)"
}

dhcpd6_service_process() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	pgrep "$1"
}

dhcpd6_service_status() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	local mods

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		${SMMS_OPENRC_PATH}/dhcpd configtest &>/dev/null && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		case "$(getDistro)" in
		"${SMMS_OS_GENTOO}")
			mods="$(grep ^dhcpd2_OPTS= /etc/conf.d/dhcpd | cut -d\" -f2)"
			;;
		esac

		dhcpd6_application_list "${mods}" -t &>/dev/null && return
		;;
	esac

	return 1
}

#######################################
# Generate the necessary code for the monit configuration
# Arguments:
#   one command returned from the list of the xxxx_list function
# Outputs:
#   Show monit code
#######################################
dhcpd6_service_monit() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	local text name

	name="$(echo ${FUNCNAME} | cut -d_ -f1)"

	text="check process dhcpd with pidfile /run/dhcp/dhcpd.pid
    group system
    start program = \"${SMMS_SERVICE_CMD} restart --no-deps ${name}\"
    stop  program = \"${SMMS_SERVICE_CMD} stop --no-deps ${name}\"
    if failed host 127.0.0.1 port 67 type udp for 5 cycles then restart
    depends on dhcpd_bin
"
	MonitMakeFile "${text}"
}
