#!/usr/bin/env bash

dhcpd4_service_list() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	SMMS_SERVICE_INIT dhcpd4.service dhcpd
}

# shellcheck disable=SC2120
dhcpd4_service_cmd() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	dhcpd_application_list
}

dhcpd4_service_name() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	echo "DHCPv4 Server Daemon"
}

dhcpd4_service_info() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	applications_vv "$(dhcpd4_service_cmd)"
}

dhcpd4_service_process() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	pgrep "$1"
}

dhcpd4_service_status() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	local mods

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		${SMMS_OPENRC_PATH}/dhcpd configtest &>/dev/null && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		case "$(getDistro)" in
		"${SMMS_OS_GENTOO}")
			mods="$(grep ^dhcpd2_OPTS= /etc/conf.d/dhcpd | cut -d\" -f2)"
			;;
		esac

		dhcpd4_application_list "${mods}" -t &>/dev/null && return
		;;
	esac

	return 1
}

#######################################
# Generate the necessary code for the monit configuration
# Arguments:
#   one command returned from the list of the xxxx_list function
# Outputs:
#   Show monit code
#######################################
dhcpd4_service_monit() {
	entry_function "${FUNCNAME}" "${FUNCNAME[1]}" "$@"

	local deps text name

	name="$(echo ${FUNCNAME} | cut -d_ -f1)"

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		pid="pidfile /run/dhcp/dhcpd.pid"
		;;
	"${SMMS_INIT_SYSTEMD}")
		pid="matching dhcpd"
		;;
	esac

	deps=$(SMMS_SERVICE_DEPS dhcpd)
	text=$(echo -e "$(eval "echo -e \"$(echo -e "$(CheckTMPL "monit")")\" ")")

	MonitMakeFile "${text}"
}
