#!/usr/bin/env bash

phpfpm_service_list() {
	local PHP

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		pushd "/etc/init.d/" &>/dev/null || return 1
		for PHP in php5.{0..6} php7.{0..4} php8.{0..4}; do
			test -x "${PHP}" && echo "${PHP}" "php-fpm@$(getVersion "$PHP").service"
		done
		;;
	"${SMMS_INIT_SYSTEMD}")
		pushd "/lib/systemd/system/" &>/dev/null || return 1
		for PHP in php-fpm@5.{0..6}.* php-fpm@7.{0..4}.* php-fpm@8.{0..4}.*; do
			test -e "${PHP}" && echo "${PHP}" "php$(getVersion "${PHP}")"
		done
		;;
	esac

	popd &>/dev/null || return
}

phpfpm_service_exixts() {
	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		/etc/init.d/${1} configtest && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		php-fpm$(getVersion "$1") -t /etc/php/fpm-php$(getVersion "$1")/php-fpm.conf -t && return
		;;
	esac

	return 1
}

phpfpm_service_name() {
	echo "The PHP FastCGI Process Manager"
}

phpfpm_service_cmd() {
	WHICH "php-fpm$(getVersion "$1")"
}

phpfpm_service_info() {
	applications_version "php-fpm$(getVersion "$1")"
}

phpfpm_service_status() {
	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		/etc/init.d/${1} configtest &>/dev/null && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		$(phpfpm_service_cmd "$1") -t -y /etc/php/fpm-php$(getVersion "$1")/php-fpm.conf &>/dev/null && return
		;;
	esac

	return 1
}
