#!/usr/bin/env bash

phpfpm_service_list() {
	entry_function ${FUNCNAME} "$@"

	local PHP

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		pushd "/etc/init.d/" &>/dev/null || return 1
		for PHP in php5.{0..6} php7.{0..4} php8.{0..4}; do
			test -x "${PHP}" && (
				echo "${PHP}"
				[[ "$1" != "only" ]] && echo "php-fpm@$(getVersion "$PHP").service"
			)
		done
		;;
	"${SMMS_INIT_SYSTEMD}")
		pushd "/lib/systemd/system/" &>/dev/null || return 1
		for PHP in php-fpm@5.{0..6}.* php-fpm@7.{0..4}.* php-fpm@8.{0..4}.*; do
			test -e "${PHP}" && (
				echo "php-fpm@$(getVersion "$PHP").service"
				[[ "$1" != "only" ]] && echo "${PHP}"
			)
		done
		;;
	esac

	popd &>/dev/null || return
}

phpfpm_service_name() {
	entry_function ${FUNCNAME} "$@"

	echo "The PHP FastCGI Process Manager"
}

phpfpm_service_cmd() {
	entry_function ${FUNCNAME} "$@"

	WHICH "php-fpm$(getVersion "$1")"
}

phpfpm_service_info() {
	entry_function ${FUNCNAME} "$@"

	applications_version "php-fpm$(getVersion "$1")"
}

phpfpm_service_status() {
	entry_function ${FUNCNAME} "$@"

	case "$(InitSystem)" in
	"${SMMS_INIT_OPENRC}")
		/etc/init.d/${1} configtest &>/dev/null && return
		;;
	"${SMMS_INIT_SYSTEMD}")
		$(phpfpm_service_cmd "$1") -t -y /etc/php/fpm-php$(getVersion "$1")/php-fpm.conf &>/dev/null && return
		;;
	esac

	return 1
}
